import numpy as np
import matplotlib.pyplot as plt


# ---------------------------------------------------------
# Target Distribution
# ---------------------------------------------------------
# This function defines the probability density we want to sample from.
# Note: The distribution does NOT need to be normalized.
# MCMC only requires the distribution up to a proportional constant.

def target_distribution(x):
    return np.exp(-x**4 + x**2)


# ---------------------------------------------------------
# Metropolis-Hastings Sampler
# ---------------------------------------------------------
# Parameters
# n_samples: number of samples to generate
# proposal_std: standard deviation of the proposal distribution

def metropolis_hastings(n_samples, proposal_std=1.0):

    samples = []

    # Initialize the chain
    current = 0

    for i in range(n_samples):

        # Step 1: Propose a new candidate state
        # We sample from a Gaussian distribution centered at the current state
        proposal = np.random.normal(current, proposal_std)

        # Step 2: Compute the acceptance ratio
        # This compares how likely the proposal is relative to the current state
        p_current = target_distribution(current)
        p_proposal = target_distribution(proposal)

        acceptance_ratio = p_proposal / p_current

        # Step 3: Accept or reject the proposal
        # Draw a random number between 0 and 1
        u = np.random.rand()

        # Accept the proposal with probability equal to the acceptance ratio
        if u < acceptance_ratio:
            current = proposal

        # Store the current state
        samples.append(current)

    return np.array(samples)


# ---------------------------------------------------------
# Run the sampler
# ---------------------------------------------------------

samples = metropolis_hastings(50000)

# Remove burn-in samples
# The initial samples may not represent the stationary distribution yet
samples = samples[1000:]


# ---------------------------------------------------------
# Visualization
# ---------------------------------------------------------
# Compare the sampled distribution with the true distribution

x = np.linspace(-2, 2, 1000)
y = target_distribution(x)

plt.figure(figsize=(8, 5))

# Histogram of samples generated by MCMC
plt.hist(samples, bins=80, density=True, alpha=0.6, label="MCMC Samples")

# Plot the true distribution (normalized for visualization)
plt.plot(x, y / np.trapz(y, x), linewidth=2, label="True Distribution")

plt.legend()
plt.title("Metropolis-Hastings Sampling")
plt.xlabel("x")
plt.ylabel("Density")

plt.show()
